stages:
  - check
  - deploy

default:
  image: "registry.gitlab.com/companionlabs-opensource/classy-fastapi:v003"
  before_script:
    - 'echo "protected: $CI_COMMIT_REF_PROTECTED. Tag: $CI_COMMIT_TAG"'

check:
  stage: check
  script:
    - ./check.sh

pypi:
  stage: deploy
  script:
    - echo Branch is $CI_COMMIT_BRANCH and tag is $CI_COMMIT_TAG. Deploying.
    - echo Comparing _v$(poetry version -s)_ and _$CI_COMMIT_TAG_ to ensure git tag and pyproject.toml versions match
    # Make sure the tag and the version in the .toml file match
    - "[[ v$(poetry version -s) == $CI_COMMIT_TAG ]]"
    - echo pyproject.toml version matches the tag. Pushing to pypi.
    - poetry publish -u __token__ -p "$PYPI_TOKEN" --build
    - echo "Deployment complete!"
  rules:
    # Only deploy if on the default (protected) branch and there's a tag that looks like a version tag.
    - if: $CI_COMMIT_REF_PROTECTED && $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+.*/

