stages:
  - check
  - deploy

default:
  image: "registry.gitlab.com/companionlabs-opensource/classy-fastapi:v003"
  before_script:
    - 'echo "protected: $CI_COMMIT_REF_PROTECTED. Tag: $CI_COMMIT_TAG"'

check:
  stage: check
  script:
    - ./check.sh

# Per https://stackoverflow.com/q/62756669/1431244 and https://gitlab.com/gitlab-org/gitlab-foss/-/issues/27818
# You can't check that the branch is master because the branch info isn't available if it's tagged but you can tell if
# it's protected which is what we want.
pypi:
  stage: deploy
  script:
    - echo Branch is $CI_COMMIT_BRANCH and tag is $CI_COMMIT_TAG. Deploying.
    # Make sure the tag and the version in the .toml file match
    - "[[ v$(poetry version -s) == $CI_COMMIT_TAG ]]"
    - poetry publish -u __token__ -p "$PYPI_TOKEN" --build
  rules:
    # Only deploy if on the default (protected) branch and there's a tag that looks like a version tag.
    - if: $CI_COMMIT_REF_PROTECTED && $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+.*/

